title: Inovasi Bisnis Inklusif
email: admin@inobisif.id
description: >-
  Inovasi Bisnis Inklusif melakukan riset, menciptakan ekosistem,
  dan mengadakan program-program inti untuk ekonomi Indonesia.
baseurl: ""
url: "http://www.inobisif.id"
twitter_username: inobisif
github_username:  code4nation
markdown: kramdown
